---
name: bluenoc
description: Immutable Fedora Silverblue with Niri and Noctalia
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr: []
      urls:
        - https://repos.fyralabs.com/terra43/terra.repo
    install:
      packages:
        - niri
        - xdg-desktop-portal-gtk
        - xwayland-satellite
        - noctalia-shell
        - brightnessctl
        - ImageMagick
        - python3
        - qt6-qtmultimedia
        - wl-clipboard
        - cliphist
        - kitty
        - plasma-polkit-agent
        - grim
        - wlsunset
        - power-profiles-daemon
        - nautilus-python
    remove:
      packages:
        - gnome-software
        - gnome-software-rpm-ostree
        - gnome-tour
        - gnome-maps
        - gnome-weather
        - gnome-contacts
        - gnome-calendar
        - gnome-clocks
        - gnome-connections
        - gnome-characters
        - gnome-calculator
        - gnome-text-editor
        - gnome-system-monitor
        - gnome-logs
        - baobab
        - file-roller
        - totem
        - rhythmbox
        - evince
        - loupe
        - gnome-classic-session
        - gnome-initial-setup
        - firefox
        - firefox-langpacks
        - ptyxis

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse

  - type: signing
