---
name: bluenoc
description: Fedora Silverblue with Niri and Noctalia
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkg.claude-desktop-debian.dev/rpm/claude-desktop.repo
    install:
      packages:
        # compositor
        - niri
        - xwayland-satellite
        # shell
        - noctalia
        # terminal
        - kitty
        # backup
        - restic
        # other
        - wl-mirror
        - network-manager-applet
        - wtype
        - claude-desktop
        - qrencode
    remove:
      packages:
        - gnome-software
        - gnome-tour
        - gnome-system-monitor
        - gnome-classic-session
        - gnome-initial-setup
        - gnome-user-docs
        - gnome-user-share
        - gnome-remote-desktop
        - yelp
        - yelp-libs
        - yelp-xsl
        - malcontent-control
        - firefox
        - firefox-langpacks
        - ptyxis
        - nvtop
        - nano
        - b43-fwcutter
        - b43-openfwwf
        - brcmfmac-firmware

  - type: containerfile
    snippets:
      - RUN dnf install -y --setopt=tsflags=noscripts displaylink && dnf clean all
      - |
        RUN KVER="$(rpm -q --qf '%{VERSION}-%{RELEASE}.%{ARCH}' kernel-core | tail -n1)" && \
            dnf install -y "kernel-devel-${KVER}" akmod-evdi && \
            akmods --force --kernels "${KVER}" --kmod evdi && \
            dnf install -y /var/cache/akmods/evdi/kmod-evdi-*.rpm && \
            depmod -a "${KVER}" && \
            rpm -e --nodeps "kernel-devel-matched-${KVER}" "kernel-devel-${KVER}" && \
            rpm -q kernel-core && \
            dnf clean all && rm -rf /var/cache/akmods/*
  
  - type: systemd
    system:
      enabled:
        - displaylink.service
    user:
      enabled:
        - topgrade.timer
        - restic-backup.timer
        
  - type: brew
    brew-analytics: false

  - type: signing
